'use strict';
(() => {
 const $=id=>document.getElementById(id), BANK=window.QUESTION_BANK, KEY='english-horse-adventure-v1';
 const HORSES=[{name:'Maple',description:'Your cheerful trail buddy',coat:'#b77443',dark:'#5c3928',light:'#e7b887'},{name:'Cloud',description:'A gentle, bright explorer',coat:'#ecebdc',dark:'#9b9a90',light:'#ffffff'},{name:'Midnight',description:'A bold little adventurer',coat:'#485464',dark:'#252f3b',light:'#778599'},{name:'Honey',description:'A sunny, curious companion',coat:'#dcad55',dark:'#926238',light:'#ffe1a0'}];
 let stored={},storageOK=true;try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch{storageOK=false;}
 let settings={horse:Number.isInteger(stored.settings?.horse)&&stored.settings.horse>=0&&stored.settings.horse<4?stored.settings.horse:0,level:['Beginner','Intermediate','Advanced'].includes(stored.settings?.level)?stored.settings.level:'Beginner',muted:stored.settings?.muted===true,reduced:typeof stored.settings?.reduced==='boolean'?stored.settings.reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
 let stats={};for(const level of ['Beginner','Intermediate','Advanced']){const s=stored.stats?.[level];stats[level]={best:Number.isInteger(s?.best)&&s.best>=0&&s.best<=500?s.best:0,runs:Number.isInteger(s?.runs)&&s.runs>=0?s.runs:0};}
 let saved=Adventure.restore(BANK,stored.game),game=null,inGame=false,keys=new Set(),last=performance.now(),lastSave=0,walk=0,toastTimer,audio;
 const modal=$('modal'),body=$('modalBody'),backdrop=new Image();backdrop.src='assets/meadow.png';
 function persist(){try{localStorage.setItem(KEY,JSON.stringify({settings,stats,game:game?game.snapshot():saved?.snapshot()||null}));}catch{if(storageOK)toast('Progress cannot be saved in this browser.');storageOK=false;}}
 function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3300);}
 function clearMovement(){keys.clear();}
 function stopSpeech(){if('speechSynthesis' in window)speechSynthesis.cancel();}
 function playTone(success=true){if(settings.muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});[0,1,2].slice(0,success?3:1).forEach((_,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.09;o.type='sine';o.frequency.value=success?[523,659,784][i]:250;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.08,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.19);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.2);});}catch{}}
 function speak(text){if(settings.muted){toast('Sound is muted. Turn it on in Settings.');return;}if(!('speechSynthesis' in window)){toast('Pronunciation is not available in this browser.');return;}stopSpeech();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=.85;const voice=speechSynthesis.getVoices().find(v=>/^en[-_]/i.test(v.lang));if(voice)utterance.voice=voice;utterance.onerror=e=>{if(!['canceled','interrupted'].includes(e.error))toast('Speech is unavailable. Please check your device voices.');};speechSynthesis.speak(utterance);}
 function updateHome(){
  $('horseLabel').textContent=HORSES[settings.horse].name;$('difficultyLabel').textContent=settings.level;
  const resumable=saved&&saved.phase!=='complete';$('resume').hidden=!resumable;
  $('savedLabel').textContent=resumable?'Your adventure is saved':'Made for curious minds';
  $('record').textContent=stats[settings.level].runs?`${settings.level} personal best: ${stats[settings.level].best} points`:'Learn at your own pace';
  $('soundToggle').textContent=settings.muted?'♪̸':'♫';$('soundToggle').setAttribute('aria-label',settings.muted?'Unmute sound':'Mute sound');$('soundToggle').title=settings.muted?'Unmute sound':'Mute sound';
 }
 function open(html){clearMovement();body.innerHTML=html;if(!modal.open)modal.showModal();}
 function close(){modal.close();stopSpeech();if(inGame&&game?.phase==='riding')$('gameCanvas').focus({preventScroll:true});}
 function heading(title,eyebrow='YOUR ADVENTURE',canClose=true){return `<div class="modal-top"><span class="eyebrow">${eyebrow}</span>${canClose?'<button class="close" id="closeModal" aria-label="Close">×</button>':''}</div><h2 id="modalTitle">${title}</h2>`;}
 function wireClose(){if($('closeModal'))$('closeModal').onclick=close;}
 function chooseHorse(){open(heading('Meet your trail buddy.')+'<p class="modal-description">Different looks. The same great adventure.</p><div class="horse-options">'+HORSES.map((h,i)=>`<button class="horse-option" data-horse="${i}" aria-pressed="${settings.horse===i}"><canvas width="240" height="130" aria-hidden="true"></canvas><strong>${h.name}</strong><small>${h.description}</small></button>`).join('')+'</div><button class="primary full" id="done">Let’s ride together</button>');wireClose();document.querySelectorAll('[data-horse]').forEach(button=>{drawHorse(button.querySelector('canvas').getContext('2d'),115,104,1,Number(button.dataset.horse),0);button.onclick=()=>{settings.horse=Number(button.dataset.horse);persist();updateHome();chooseHorse();};});$('done').onclick=close;}
 function chooseDifficulty(){const details=['Colors, animals & your first sentences','New words, everyday grammar & more','Tricky grammar, meaning & expression'];open(heading('Choose your challenge.')+'<p class="modal-description">Every level has five stops. Take as many tries as you need.</p>'+['Beginner','Intermediate','Advanced'].map((level,i)=>`<button class="difficulty-option" data-level="${level}" aria-pressed="${settings.level===level}"><span><strong>${level}</strong><small>${details[i]}</small></span><span>${'✦'.repeat(i+1)}</span></button>`).join(''));wireClose();document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{settings.level=b.dataset.level;persist();updateHome();close();});}
 function how(){open(heading('A small guide to a big adventure.')+'<ol class="how-list"><li>Choose your horse and difficulty, then press <strong>Play</strong>.</li><li>Ride right with <strong>D or →</strong>. Use <strong>A or ←</strong> to go back. <strong>W / S or ↑ / ↓</strong> move you across the trail. On a phone, hold the arrow buttons.</li><li>Your horse stops at every <strong>STOP</strong> sign. Pick the right answer to continue. A hint will help if you need another try.</li><li>Earn <strong>100 points</strong> on your first try, <strong>60</strong> on your second, or <strong>40</strong> after that. Finish all five stops and ride to the flag!</li></ol><p class="modal-description">Stars: 3 for 4–5 first-try answers, 2 for 2–3, and 1 for 0–1. Your progress saves automatically on this device.</p><button class="primary full" id="done">Got it!</button>');wireClose();$('done').onclick=close;}
 function showSettings(){open(heading('Make yourself comfortable.')+`<label class="settings-row">Mute sound<input id="muteSetting" type="checkbox" ${settings.muted?'checked':''}></label><label class="settings-row">Reduce animation<input id="motionSetting" type="checkbox" ${settings.reduced?'checked':''}></label><p class="modal-description">Pronunciation uses your device’s English voice. Voice availability depends on your browser and device.</p><p class="modal-description">${storageOK?'Your progress and settings stay on this device.':'Local saving is unavailable in this browser.'}</p><button class="primary full" id="done">Save settings</button>`);wireClose();$('muteSetting').onchange=e=>{settings.muted=e.target.checked;if(settings.muted)stopSpeech();persist();updateHome();};$('motionSetting').onchange=e=>{settings.reduced=e.target.checked;persist();};$('done').onclick=close;}
 function start(resume=false){
  if(!resume&&saved&&saved.phase!=='complete'){open(heading('Start a fresh trail?')+'<p class="modal-description">This replaces your saved trail. Your personal bests will stay.</p><button class="primary full" id="newTrail">Start New Adventure</button><button class="secondary full" id="keepTrail">Keep My Saved Trail</button>');wireClose();$('newTrail').onclick=()=>{saved=null;game=null;close();start();};$('keepTrail').onclick=()=>{close();start(true);};return;}
  game=resume&&saved?saved:new Adventure(BANK,settings.level);saved=null;game.resume();inGame=true;$('home').hidden=true;$('game').hidden=false;clearMovement();if(modal.open)close();hud();persist();window.scrollTo(0,0);$('gameCanvas').focus({preventScroll:true});if(['question','feedback'].includes(game.phase))question();
 }
 function hud(){if(!game)return;$('score').textContent=game.score;$('progress').value=game.completed;$('progressText').textContent=`${game.completed} / 5`;$('remaining').textContent=5-game.completed;$('levelLabel').textContent=`${game.level.toUpperCase()} • SUNNY MEADOW`;$('nextStop').textContent=game.completed<5?`Next stop: ${game.completed+1}`:'Ride to the finish!';$('rideStatus').textContent=game.completed===5?'All stops cleared! The finish is ahead.':game.completed?`Great work! On to stop ${game.completed+1}.`:'Let’s go, explorer!';}
 function question(){
  const q=game.question;if(!q)return;const answered=game.phase==='feedback';
  open(heading(q.prompt,`LEARNING STOP ${game.completed+1} OF 5`,false)+`<div class="question-meta"><span class="category">${q.category}</span><span class="category">${game.level}</span><button class="listen" id="listen">♫ Listen</button></div><div class="answers">${q.options.map((option,i)=>`<button class="answer${answered&&i===q.answer?' correct':''}" data-answer="${i}" ${answered?'disabled':''}><span>${'ABCD'[i]}</span>${option}</button>`).join('')}</div><div id="feedback" class="feedback${answered?' success':''}" role="status">${answered?`<strong>Well done!</strong> +${game.earned[game.completed]} points. You’re ready to ride!`:game.attempts[game.completed]?`<strong>Try again!</strong> ${q.hint}`:''}</div><button class="primary full" id="continueRide" ${answered?'':'hidden'}>Continue Riding →</button><button class="secondary full" id="questionPause">Pause Adventure</button>`);
  $('listen').onclick=()=>speak(game.phase==='feedback'?q.speak:q.prompt);
  document.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>{
   const result=game.answer(Number(button.dataset.answer));if(!result)return;persist();hud();
   if(result.correct){playTone();document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);button.classList.add('correct');$('feedback').className='feedback success';$('feedback').innerHTML=`<strong>Well done!</strong> +${result.points} points. You’re ready to ride!`;$('continueRide').hidden=false;$('continueRide').focus();}
   else{playTone(false);button.classList.add('wrong');button.disabled=true;$('feedback').className='feedback error';$('feedback').innerHTML=`<strong>Try again!</strong> ${q.hint}`;}
  });
  $('continueRide').onclick=()=>{if(game.continue()){persist();hud();close();}};$('questionPause').onclick=pause;
 }
 function pause(){if(!inGame||!game||game.phase==='complete')return;game.pause();clearMovement();stopSpeech();persist();open(heading('A little breather.', 'ADVENTURE PAUSED',false)+'<p class="modal-description">Your horse is resting and your progress is saved.</p><button class="primary full" id="resumeRide">Resume Adventure</button><button class="secondary full" id="goHome">Save & Return Home</button>');$('resumeRide').onclick=()=>{game.resume();close();if(game.phase!=='riding')question();persist();};$('goHome').onclick=goHome;}
 function goHome(){clearMovement();stopSpeech();if(game){if(game.phase!=='complete')game.pause();saved=game;}game=null;inGame=false;persist();close();$('home').hidden=false;$('game').hidden=true;updateHome();window.scrollTo(0,0);$('play').focus({preventScroll:true});}
 function finish(){stats[game.level].best=Math.max(stats[game.level].best,game.score);stats[game.level].runs++;persist();clearMovement();playTone();open(heading('You did it, explorer!', 'TRAIL COMPLETE',false)+`<div class="result-icon" aria-label="${game.stars} out of 3 stars">${'★'.repeat(game.stars)}<span style="color:#dce3d6">${'☆'.repeat(3-game.stars)}</span></div><p class="modal-description result-heading">Five stops, five discoveries.<br>Look how far you’ve come!</p><div class="result-stats"><div><strong>${game.score}</strong><small>Total points</small></div><div><strong>${game.firstTry} / 5</strong><small>First-try answers</small></div><div><strong>5 / 5</strong><small>Stops completed</small></div></div><p class="modal-description result-heading">${game.level} personal best: ${stats[game.level].best} points</p><button class="primary full" id="playAgain">Play Again</button><button class="secondary full" id="finishHome">Return Home</button>`);$('playAgain').onclick=()=>{settings.level=game.level;game=null;saved=null;close();start();};$('finishHome').onclick=goHome;}
 $('play').onclick=()=>start();$('resume').onclick=()=>start(true);$('horseMenu').onclick=chooseHorse;$('difficultyMenu').onclick=chooseDifficulty;$('howMenu').onclick=how;$('settingsMenu').onclick=showSettings;$('pause').onclick=pause;
 $('soundToggle').onclick=()=>{settings.muted=!settings.muted;if(settings.muted)stopSpeech();persist();updateHome();};
 document.querySelector('.brand').onclick=e=>{e.preventDefault();if(inGame)pause();};
 modal.addEventListener('cancel',e=>{if(inGame){e.preventDefault();if(game.phase==='paused'){$('resumeRide')?.click();}else pause();}});
 const mapping={ArrowRight:'right',KeyD:'right',ArrowLeft:'left',KeyA:'left',ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down'};
 addEventListener('keydown',e=>{if(!inGame)return;if(e.code==='Escape'&&!modal.open){e.preventDefault();pause();return;}if(mapping[e.code]&&game.phase==='riding'&&!modal.open){e.preventDefault();keys.add(mapping[e.code]);}});
 addEventListener('keyup',e=>{if(mapping[e.code])keys.delete(mapping[e.code]);});
 document.querySelectorAll('[data-dir]').forEach(button=>{button.addEventListener('pointerdown',e=>{e.preventDefault();if(game?.phase==='riding'){button.setPointerCapture(e.pointerId);keys.add(button.dataset.dir);}});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>keys.delete(button.dataset.dir));button.addEventListener('contextmenu',e=>e.preventDefault());});
 addEventListener('blur',()=>{clearMovement();if(inGame&&game?.phase==='riding')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearMovement();if(inGame&&game?.phase==='riding')pause();persist();}});addEventListener('pagehide',persist);
 // Original procedural horse sprite. Its articulated legs react to movement.
 function drawHorse(ctx,x,y,scale,index,step=0,facing=1){
  const h=HORSES[index];ctx.save();ctx.translate(x,y);ctx.scale(scale*facing,scale);
  ctx.fillStyle='#22452d25';ctx.beginPath();ctx.ellipse(0,0,63,10,0,0,Math.PI*2);ctx.fill();ctx.translate(0,-6-Math.abs(Math.sin(step*2))*2);
  ctx.lineCap='round';ctx.lineJoin='round';
  // Tail, far legs, near legs, body, mane and head are drawn in depth order.
  ctx.strokeStyle=h.dark;ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(-46,-58);ctx.bezierCurveTo(-75,-65,-60,-26,-79,-22);ctx.stroke();
  function leg(x,phase,dark){const a=Math.sin(step+phase)*17;ctx.strokeStyle=dark?h.dark:h.coat;ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(x,-48);ctx.lineTo(x+a*.6,-25);ctx.lineTo(x+a,0);ctx.stroke();ctx.strokeStyle='#384039';ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(x+a-2,1);ctx.lineTo(x+a+5,1);ctx.stroke();}
  leg(-33,Math.PI,true);leg(33,0,true);leg(-42,0,false);leg(22,Math.PI,false);
  ctx.fillStyle=h.coat;ctx.beginPath();ctx.ellipse(-5,-58,55,30,.05,0,Math.PI*2);ctx.fill();
  ctx.fillStyle=h.light;ctx.globalAlpha=.35;ctx.beginPath();ctx.ellipse(-13,-49,34,12,.12,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
  ctx.fillStyle=h.coat;ctx.beginPath();ctx.moveTo(16,-66);ctx.bezierCurveTo(26,-83,21,-112,36,-115);ctx.bezierCurveTo(47,-118,54,-103,57,-92);ctx.lineTo(42,-49);ctx.closePath();ctx.fill();
  ctx.fillStyle=h.dark;ctx.beginPath();ctx.moveTo(31,-111);ctx.bezierCurveTo(8,-105,24,-85,14,-75);ctx.lineTo(28,-79);ctx.lineTo(40,-108);ctx.fill();
  ctx.fillStyle=h.coat;ctx.beginPath();ctx.ellipse(49,-108,23,19,.35,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(66,-99,21,13,.23,0,Math.PI*2);ctx.fill();
  ctx.beginPath();ctx.moveTo(32,-119);ctx.lineTo(31,-144);ctx.quadraticCurveTo(48,-140,45,-119);ctx.fill();ctx.beginPath();ctx.moveTo(49,-124);ctx.lineTo(56,-145);ctx.quadraticCurveTo(64,-135,59,-119);ctx.fill();
  ctx.strokeStyle=h.light;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(54,-116);ctx.lineTo(65,-103);ctx.stroke();
  ctx.fillStyle='#202e29';ctx.beginPath();ctx.arc(51,-111,3.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(52,-112,1.1,0,Math.PI*2);ctx.fill();ctx.fillStyle=h.dark;ctx.beginPath();ctx.ellipse(78,-99,2,2.7,.3,0,Math.PI*2);ctx.fill();
  ctx.strokeStyle='#634333';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(70,-95,8,.4,1.6);ctx.stroke();
  ctx.fillStyle='#286956';ctx.beginPath();ctx.roundRect(-26,-86,47,27,[4,4,12,12]);ctx.fill();ctx.strokeStyle='#f2ca6c';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-20,-63);ctx.lineTo(15,-63);ctx.stroke();ctx.fillStyle='#613d2c';ctx.beginPath();ctx.roundRect(-23,-89,41,9,4);ctx.fill();
  ctx.strokeStyle='#70503a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(69,-110);ctx.lineTo(62,-91);ctx.bezierCurveTo(42,-71,12,-77,6,-85);ctx.stroke();ctx.restore();
 }
 function canvasSize(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return {ctx,w:r.width,h:r.height};}
 function background(ctx,w,h,home=false){
  ctx.fillStyle='#bfe6df';ctx.fillRect(0,0,w,h);
  if(backdrop.complete&&backdrop.naturalWidth){const s=Math.max(w/backdrop.width,h/backdrop.height);ctx.drawImage(backdrop,(w-backdrop.width*s)/2,(h-backdrop.height*s)/2,backdrop.width*s,backdrop.height*s);}
  else{ctx.fillStyle='#84b969';ctx.fillRect(0,h*.45,w,h*.55);}
  if(home){const g=ctx.createLinearGradient(0,0,0,h*.7);g.addColorStop(0,'#d9f0e9e8');g.addColorStop(1,'#d9f0e900');ctx.fillStyle=g;ctx.fillRect(0,0,w,h*.7);}
 }
 function pathY(x,h){return h*.74+Math.sin(x/290)*h*.042;}
 function drawTrack(ctx,w,h,camera){for(const [width,color] of [[76,'#d3ae73'],[64,'#edcf95']]){ctx.beginPath();for(let sx=-20;sx<=w+20;sx+=10){const y=pathY(sx+camera,h);if(sx===-20)ctx.moveTo(sx,y);else ctx.lineTo(sx,y);}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}ctx.setLineDash([3,32]);ctx.strokeStyle='#d3b077';ctx.lineWidth=2;ctx.beginPath();for(let x=-20;x<=w+20;x+=10){const y=pathY(x+camera,h);if(x===-20)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();ctx.setLineDash([]);}
 function sign(ctx,x,y,done,num){
  ctx.fillStyle='#7c6445';ctx.fillRect(x-3,y-60,6,65);ctx.fillStyle='#ffffff';ctx.beginPath();for(let i=0;i<8;i++){const a=Math.PI/8+i*Math.PI/4;const px=x+29*Math.cos(a),py=y-79+29*Math.sin(a);i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fill();ctx.fillStyle=done?'#3c8354':'#bc5041';ctx.beginPath();for(let i=0;i<8;i++){const a=Math.PI/8+i*Math.PI/4;const px=x+25*Math.cos(a),py=y-79+25*Math.sin(a);i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fill();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`bold ${done?23:12}px Trebuchet MS`;ctx.fillStyle='#fff';ctx.fillText(done?'✓':'STOP',x,y-79);ctx.fillStyle='#fffdf3';ctx.beginPath();ctx.arc(x,y+15,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#526448';ctx.font='bold 11px Trebuchet MS';ctx.fillText(num,x,y+15);
 }
 function renderHome(){const {ctx,w,h}=canvasSize($('homeCanvas'));if(!w)return;background(ctx,w,h,true);ctx.save();ctx.globalAlpha=.9;drawTrack(ctx,w,h,200);ctx.restore();const small=w<450,scale=small?.66:1.2;drawHorse(ctx,w*.63,h*(small?.9:.79),scale,settings.horse,0);sign(ctx,w*.88,h*(small?.89:.73),false,1);}
 function renderGame(dt){const {ctx,w,h}=canvasSize($('gameCanvas'));if(!w)return;const camera=Math.max(0,game.x-w*.28);background(ctx,w,h);drawTrack(ctx,w,h,camera);
  for(let i=0;i<5;i++){const sx=Adventure.STOPS[i]-camera;if(sx>-50&&sx<w+60){sign(ctx,sx,pathY(Adventure.STOPS[i],h)-34,i<game.completed,i+1);if(i>=game.completed){ctx.strokeStyle='#ffffff85';ctx.lineWidth=5;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(sx,pathY(Adventure.STOPS[i],h)-28);ctx.lineTo(sx,pathY(Adventure.STOPS[i],h)+28);ctx.stroke();ctx.setLineDash([]);}}}
  const flagX=Adventure.FINISH-camera;if(flagX>-50&&flagX<w+60){const y=pathY(Adventure.FINISH,h);ctx.fillStyle='#735e41';ctx.fillRect(flagX-3,y-139,6,140);for(let r=0;r<4;r++)for(let c=0;c<5;c++){ctx.fillStyle=(r+c)%2?'#fffdf0':'#244b3b';ctx.fillRect(flagX+c*10,y-139+r*10,10,10);}ctx.fillStyle='#234c3c';ctx.font='bold 11px Trebuchet MS';ctx.textAlign='center';ctx.fillText('FINISH',flagX,y+24);}
  const moving=game.phase==='riding'&&keys.size>0;if(moving&&!settings.reduced)walk+=dt*11;
  drawHorse(ctx,game.x-camera,pathY(game.x,h)+game.lane+6,w<500?.68:.85,settings.horse,moving&&!settings.reduced?walk:0,keys.has('left')&&!keys.has('right')?-1:1);
 }
 function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;
  if(inGame&&game){if(game.phase==='riding'&&!modal.open){const before=game.phase;game.move(((keys.has('right')?1:0)-(keys.has('left')?1:0))*230*dt,((keys.has('down')?1:0)-(keys.has('up')?1:0))*100*dt);if(game.phase!==before){clearMovement();persist();if(game.phase==='question')question();else if(game.phase==='complete')finish();}else if(keys.size&&now-lastSave>700){persist();lastSave=now;}}
   renderGame(dt);
  }else renderHome();requestAnimationFrame(frame);
 }
 updateHome();requestAnimationFrame(frame);
})();
